version: '3.8'

services:
  tipocambio:
    image: tipocambio:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - h2

  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
